export const APP_CATALOGUE: Record<string, { display_name: string; package_name: string; icon: string }[]> = {
  email: [
    { display_name: 'Gmail', package_name: 'com.google.android.gm', icon: '📧' },
    { display_name: 'Outlook', package_name: 'com.microsoft.outlook', icon: '📨' },
    { display_name: 'Proton Mail', package_name: 'ch.protonmail.android', icon: '🔒' },
    { display_name: 'Spark', package_name: 'com.readdle.spark', icon: '⚡' },
    { display_name: 'Thunderbird', package_name: 'net.thunderbird.android', icon: '🦅' },
    { display_name: 'Yahoo Mail', package_name: 'com.yahoo.mobile.client.android.mail', icon: '📬' },
    { display_name: 'Samsung Email', package_name: 'com.samsung.android.email.provider', icon: '📩' },
    { display_name: 'Tutanota', package_name: 'de.tutao.tutanota', icon: '🔐' },
  ],
  tel: [
    { display_name: 'Google Phone', package_name: 'com.google.android.dialer', icon: '📞' },
    { display_name: 'Samsung Phone', package_name: 'com.samsung.android.dialer', icon: '📱' },
    { display_name: 'Truecaller', package_name: 'com.truecaller', icon: '✅' },
    { display_name: 'Skype', package_name: 'com.skype.raider', icon: '💬' },
    { display_name: 'WhatsApp', package_name: 'com.whatsapp', icon: '💚' },
    { display_name: 'Signal', package_name: 'org.thoughtcrime.securesms', icon: '🔵' },
  ],
  geo: [
    { display_name: 'Google Maps', package_name: 'com.google.android.apps.maps', icon: '🗺️' },
    { display_name: 'Waze', package_name: 'com.waze', icon: '🚗' },
    { display_name: 'HERE WeGo', package_name: 'com.here.app.maps', icon: '📍' },
    { display_name: 'Organic Maps', package_name: 'app.organicmaps', icon: '🌿' },
    { display_name: 'OsmAnd', package_name: 'net.osmand', icon: '🧭' },
    { display_name: 'Citymapper', package_name: 'com.citymapper.app.release', icon: '🚇' },
  ],
  pdf: [
    { display_name: 'Adobe Acrobat', package_name: 'com.adobe.reader', icon: '📄' },
    { display_name: 'Xodo PDF', package_name: 'com.xodo.pdf.reader', icon: '✏️' },
    { display_name: 'Google Drive', package_name: 'com.google.android.apps.docs', icon: '☁️' },
    { display_name: 'Samsung Notes', package_name: 'com.samsung.android.app.notes', icon: '📝' },
    { display_name: 'WPS Office', package_name: 'cn.wps.moffice_eng', icon: '📊' },
    { display_name: 'Foxit PDF', package_name: 'com.foxit.mobile.pdf.lite', icon: '🦊' },
  ],
  browser: [
    { display_name: 'Chrome', package_name: 'com.android.chrome', icon: '🌐' },
    { display_name: 'Firefox', package_name: 'org.mozilla.firefox', icon: '🦊' },
    { display_name: 'Brave', package_name: 'com.brave.browser', icon: '🦁' },
    { display_name: 'Samsung Internet', package_name: 'com.sec.android.app.sbrowser', icon: '🌊' },
    { display_name: 'DuckDuckGo', package_name: 'com.duckduckgo.mobile.android', icon: '🦆' },
    { display_name: 'Opera', package_name: 'com.opera.browser', icon: '🔴' },
    { display_name: 'Edge', package_name: 'com.microsoft.emmx', icon: '🔷' },
    { display_name: 'Vivaldi', package_name: 'com.vivaldi.browser', icon: '🎵' },
  ],
  image: [
    { display_name: 'Google Photos', package_name: 'com.google.android.apps.photos', icon: '🖼️' },
    { display_name: 'Samsung Gallery', package_name: 'com.sec.android.gallery3d', icon: '🎨' },
    { display_name: 'Snapseed', package_name: 'com.niksoftware.snapseed', icon: '📸' },
    { display_name: 'VSCO', package_name: 'com.vsco.cam', icon: '✨' },
    { display_name: 'Lightroom', package_name: 'com.adobe.lrmobile', icon: '💡' },
  ],
  text: [
    { display_name: 'Google Messages', package_name: 'com.google.android.apps.messaging', icon: '💬' },
    { display_name: 'Samsung Messages', package_name: 'com.samsung.android.messaging', icon: '📲' },
    { display_name: 'Signal', package_name: 'org.thoughtcrime.securesms', icon: '🔵' },
    { display_name: 'Telegram', package_name: 'org.telegram.messenger', icon: '✈️' },
  ],
};
